# Generated by Django 5.2.5 on 2025-09-05 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaFirma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Plantilla')),
                ('descripcion', models.TextField(help_text='Descripción de la plantilla', verbose_name='Descripción')),
                ('html_template', models.TextField(help_text='Plantilla HTML con placeholders', verbose_name='HTML Template')),
                ('color_principal', models.CharField(default='#0066cc', max_length=7, verbose_name='Color Principal')),
                ('incluir_logos', models.BooleanField(default=True, verbose_name='Incluir Logos por Defecto')),
                ('activa', models.BooleanField(default=True, verbose_name='Plantilla Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Firma',
                'verbose_name_plural': 'Plantillas de Firma',
                'db_table': 'correo_masivo_plantilla_firma',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ListaRemitentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre descriptivo para identificar la lista de remitentes', max_length=100, verbose_name='Nombre de la Lista')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción opcional de la lista de remitentes', null=True, verbose_name='Descripción')),
                ('unidad', models.CharField(help_text='Unidad organizacional del usuario que creó la lista', max_length=100, verbose_name='Unidad del Usuario')),
                ('activa', models.BooleanField(default=True, verbose_name='Lista Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas_remitentes', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creador')),
            ],
            options={
                'verbose_name': 'Lista de Remitentes',
                'verbose_name_plural': 'Listas de Remitentes',
                'db_table': 'correo_masivo_lista_remitentes',
                'ordering': ['-fecha_modificacion'],
                'unique_together': {('nombre', 'usuario')},
            },
        ),
        migrations.CreateModel(
            name='FirmaCorreo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(help_text='Nombre que aparecerá en la firma', max_length=200, verbose_name='Nombre Completo')),
                ('cargo', models.CharField(help_text='Cargo o posición que ocupa', max_length=200, verbose_name='Cargo')),
                ('unidad', models.CharField(help_text='Unidad o departamento al que pertenece', max_length=300, verbose_name='Unidad/Departamento')),
                ('institucion', models.CharField(help_text='Nombre de la institución u organización', max_length=300, verbose_name='Institución')),
                ('telefono', models.CharField(help_text='Número de teléfono de contacto', max_length=50, verbose_name='Teléfono')),
                ('email', models.EmailField(help_text='Dirección de correo electrónico', max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, help_text='URL del sitio web institucional', max_length=300, verbose_name='Sitio Web')),
                ('plantilla', models.CharField(choices=[('hospital', 'Firma Hospital'), ('ministerio', 'Firma Ministerial'), ('simple', 'Firma Simple'), ('personalizada', 'Personalizada')], default='hospital', max_length=50, verbose_name='Plantilla')),
                ('html_firma', models.TextField(help_text='Código HTML completo de la firma generada', verbose_name='HTML de la Firma')),
                ('logo_gobierno', models.ImageField(blank=True, help_text='Logo del Gobierno de Chile (recomendado: 80x40px, formato PNG)', null=True, upload_to='firmas/logos/', verbose_name='Logo Gobierno de Chile')),
                ('logo_salud', models.ImageField(blank=True, help_text='Logo del Servicio de Salud (recomendado: 80x40px, formato PNG)', null=True, upload_to='firmas/logos/', verbose_name='Logo Servicio de Salud')),
                ('logo_hospital', models.ImageField(blank=True, help_text='Logo del Hospital (recomendado: 60x40px, formato PNG)', null=True, upload_to='firmas/logos/', verbose_name='Logo Hospital')),
                ('incluir_logos', models.BooleanField(default=True, help_text='Mostrar logos del gobierno, servicio de salud y hospital', verbose_name='Incluir Logos Institucionales')),
                ('color_principal', models.CharField(default='#0066cc', help_text='Color principal de la firma (formato hex: #ffffff)', max_length=7, verbose_name='Color Principal')),
                ('es_predeterminada', models.BooleanField(default=False, help_text='Usar esta firma como predeterminada para correos', verbose_name='Firma Predeterminada')),
                ('activa', models.BooleanField(default=True, help_text='Si la firma está disponible para uso', verbose_name='Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Última Modificación')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firmas_correo', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Firma de Correo',
                'verbose_name_plural': 'Firmas de Correo',
                'db_table': 'correo_masivo_firma',
                'ordering': ['-es_predeterminada', '-fecha_modificacion'],
                'indexes': [models.Index(fields=['usuario', 'activa'], name='correo_masi_usuario_33c4ff_idx'), models.Index(fields=['es_predeterminada'], name='correo_masi_es_pred_595e6e_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('es_predeterminada', True)), fields=('usuario',), name='unique_default_signature_per_user')],
            },
        ),
        migrations.CreateModel(
            name='FuncionarioEnLista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcionario_id', models.IntegerField(blank=True, help_text='ID del funcionario en PostgreSQL', null=True, verbose_name='ID del Funcionario')),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Agregado')),
                ('activo_en_lista', models.BooleanField(default=True, verbose_name='Activo en Lista')),
                ('agregado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Agregado por')),
                ('lista_remitentes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='correo_masivo.listaremitentes', verbose_name='Lista de Remitentes')),
            ],
            options={
                'verbose_name': 'Funcionario en Lista',
                'verbose_name_plural': 'Funcionarios en Lista',
                'db_table': 'correo_masivo_funcionario_en_lista',
                'ordering': ['-fecha_agregado'],
                'unique_together': {('lista_remitentes', 'funcionario_id')},
            },
        ),
    ]
