# Generated by Django 5.2.5 on 2025-09-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12)),
                ('puesto_trabajo', models.CharField(max_length=100)),
                ('razon_contacto', models.CharField(max_length=255)),
                ('mensaje', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='contactos_fotos/')),
            ],
        ),
    ]
