# Generated by Django 5.2.7 on 2025-10-25 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitud',
            options={'ordering': ['-fecha_solicitud', '-numero'], 'permissions': [('aprobar_solicitud', 'Puede aprobar solicitudes'), ('rechazar_solicitud', 'Puede rechazar solicitudes'), ('despachar_solicitud', 'Puede despachar solicitudes'), ('change_any_solicitud', 'Puede editar cualquier solicitud'), ('delete_any_solicitud', 'Puede eliminar cualquier solicitud'), ('ver_todas_solicitudes', 'Puede ver todas las solicitudes')], 'verbose_name': 'Solicitud', 'verbose_name_plural': 'Solicitudes'},
        ),
    ]
