# Generated by Django 5.2.7 on 2025-10-25 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0001_initial'),
        ('solicitudes', '0002_alter_solicitud_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='tipo',
            field=models.CharField(choices=[('ACTIVO', 'Solicitud de Activos/Bienes'), ('ARTICULO', 'Solicitud de Artículos')], default='ARTICULO', help_text='Define si la solicitud es de activos (bienes) o artículos', max_length=10, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='bodega_origen',
            field=models.ForeignKey(blank=True, help_text='Solo requerido para solicitudes de artículos. Las solicitudes de activos no tienen bodega.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_origen', to='bodega.bodega', verbose_name='Bodega Origen'),
        ),
    ]
