# Generated by Django 5.2.7 on 2025-10-28 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0004_estandarizar_basemodel'),
        ('bodega', '0001_initial'),
        ('solicitudes', '0004_solicitud_objetivo_actividad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallesolicitud',
            name='articulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_solicitud', to='bodega.articulo', verbose_name='Artículo'),
        ),
        migrations.AlterField(
            model_name='detallesolicitud',
            name='activo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_solicitud', to='activos.activo', verbose_name='Bien/Activo'),
        ),
    ]
