# Generated by Django 5.2.7 on 2025-10-25 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activo',
            options={'ordering': ['codigo'], 'permissions': [('gestionar_inventario', 'Puede gestionar inventario de activos'), ('ajustar_inventario', 'Puede realizar ajustes de inventario'), ('ver_reportes_inventario', 'Puede ver reportes de inventario'), ('importar_activos', 'Puede importar activos masivamente'), ('exportar_activos', 'Puede exportar listado de activos')], 'verbose_name': 'Activo', 'verbose_name_plural': 'Activos'},
        ),
    ]
