# Generated by Django 5.2.7 on 2025-10-25 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0002_alter_activo_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoMovimientoActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('requiere_ubicacion', models.BooleanField(default=True, verbose_name='Requiere Ubicación')),
                ('requiere_responsable', models.BooleanField(default=True, verbose_name='Requiere Responsable')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Tipo de Movimiento de Activo',
                'verbose_name_plural': 'Tipos de Movimiento de Activos',
                'db_table': 'activo_tipo_movimiento',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('edificio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Edificio')),
                ('piso', models.CharField(blank=True, max_length=20, null=True, verbose_name='Piso')),
                ('area', models.CharField(blank=True, max_length=100, null=True, verbose_name='Área/Departamento')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'db_table': 'activo_ubicacion',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(blank=True, help_text='Requerido si el activo requiere número de serie', max_length=100, null=True, verbose_name='Número de Serie')),
                ('lote', models.CharField(blank=True, help_text='Requerido si el activo requiere lote', max_length=50, null=True, verbose_name='Lote')),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Requerido si el activo requiere fecha de vencimiento', null=True, verbose_name='Fecha de Vencimiento')),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Movimiento')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_activo', to='activos.activo', verbose_name='Activo')),
                ('responsable', models.ForeignKey(blank=True, help_text='Usuario responsable del activo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activos_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('usuario_registro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Registró')),
                ('tipo_movimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='activos.tipomovimientoactivo', verbose_name='Tipo de Movimiento')),
                ('ubicacion_destino', models.ForeignKey(blank=True, help_text='Ubicación física donde se encuentra el activo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_destino', to='activos.ubicacion', verbose_name='Ubicación Destino')),
            ],
            options={
                'verbose_name': 'Movimiento de Activo',
                'verbose_name_plural': 'Movimientos de Activos',
                'db_table': 'activo_movimiento',
                'ordering': ['-fecha_movimiento'],
                'permissions': [('registrar_movimiento', 'Puede registrar movimientos de activos'), ('ver_historial_movimientos', 'Puede ver historial de movimientos')],
            },
        ),
        migrations.CreateModel(
            name='UbicacionActual',
            fields=[
                ('activo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ubicacion_actual', serialize=False, to='activos.activo', verbose_name='Activo')),
                ('fecha_ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activos_a_cargo', to=settings.AUTH_USER_MODEL, verbose_name='Responsable Actual')),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activos_actuales', to='activos.ubicacion', verbose_name='Ubicación Actual')),
                ('ultimo_movimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activos.movimientoactivo', verbose_name='Último Movimiento')),
            ],
            options={
                'verbose_name': 'Ubicación Actual de Activo',
                'verbose_name_plural': 'Ubicaciones Actuales de Activos',
                'db_table': 'activo_ubicacion_actual',
            },
        ),
        migrations.DeleteModel(
            name='InventarioActivo',
        ),
    ]
