# Generated by Django 5.2.7 on 2025-10-27 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0003_tipomovimientoactivo_ubicacion_movimientoactivo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activo',
            name='fecha_modificacion',
        ),
        migrations.RemoveField(
            model_name='categoriaactivo',
            name='activa',
        ),
        migrations.RemoveField(
            model_name='ubicacion',
            name='activa',
        ),
        migrations.RemoveField(
            model_name='unidadmedida',
            name='activa',
        ),
        migrations.AddField(
            model_name='activo',
            name='eliminado',
            field=models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado'),
        ),
        migrations.AddField(
            model_name='activo',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización'),
        ),
        migrations.AddField(
            model_name='categoriaactivo',
            name='activo',
            field=models.BooleanField(default=True, help_text='Estado activo/inactivo del registro', verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='categoriaactivo',
            name='eliminado',
            field=models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado'),
        ),
        migrations.AddField(
            model_name='categoriaactivo',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización'),
        ),
        migrations.AddField(
            model_name='estadoactivo',
            name='eliminado',
            field=models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado'),
        ),
        migrations.AddField(
            model_name='estadoactivo',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización'),
        ),
        migrations.AddField(
            model_name='tipomovimientoactivo',
            name='eliminado',
            field=models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado'),
        ),
        migrations.AddField(
            model_name='tipomovimientoactivo',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='activo',
            field=models.BooleanField(default=True, help_text='Estado activo/inactivo del registro', verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='eliminado',
            field=models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado'),
        ),
        migrations.AddField(
            model_name='ubicacion',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización'),
        ),
        migrations.AddField(
            model_name='unidadmedida',
            name='activo',
            field=models.BooleanField(default=True, help_text='Estado activo/inactivo del registro', verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='unidadmedida',
            name='eliminado',
            field=models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado'),
        ),
        migrations.AddField(
            model_name='unidadmedida',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='activo',
            field=models.BooleanField(default=True, help_text='Estado activo/inactivo del registro', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='categoriaactivo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='estadoactivo',
            name='activo',
            field=models.BooleanField(default=True, help_text='Estado activo/inactivo del registro', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='estadoactivo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='tipomovimientoactivo',
            name='activo',
            field=models.BooleanField(default=True, help_text='Estado activo/inactivo del registro', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='tipomovimientoactivo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='unidadmedida',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación'),
        ),
    ]
