# Generated by Django 5.2.7 on 2025-10-29 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0004_estandarizar_basemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveniencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, help_text='Estado activo/inactivo del registro', verbose_name='Activo')),
                ('eliminado', models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Proveniencia',
                'verbose_name_plural': 'Proveniencias',
                'db_table': 'activo_proveniencia',
                'ordering': ['codigo'],
            },
        ),
        migrations.AddField(
            model_name='movimientoactivo',
            name='fecha_baja',
            field=models.DateField(blank=True, help_text='Fecha en que el activo fue dado de baja', null=True, verbose_name='Fecha de Baja'),
        ),
        migrations.AddField(
            model_name='movimientoactivo',
            name='fecha_ingreso',
            field=models.DateField(blank=True, help_text='Fecha en que el activo ingresó al inventario', null=True, verbose_name='Fecha de Ingreso'),
        ),
        migrations.AddField(
            model_name='movimientoactivo',
            name='motivo_baja',
            field=models.TextField(blank=True, help_text='Razón por la cual el activo fue dado de baja', null=True, verbose_name='Motivo de Baja'),
        ),
        migrations.AddField(
            model_name='movimientoactivo',
            name='numero_factura_guia',
            field=models.CharField(blank=True, help_text='Número de factura o guía de remisión', max_length=100, null=True, verbose_name='Nº Factura / Guía'),
        ),
        migrations.AddField(
            model_name='movimientoactivo',
            name='proveniencia',
            field=models.ForeignKey(blank=True, help_text='Origen o procedencia del activo', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='activos.proveniencia', verbose_name='Proveniencia'),
        ),
    ]
