# Generated by Django 5.2.7 on 2025-10-31 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activos', '0005_proveniencia_movimientoactivo_fecha_baja_and_more'),
        ('inventario', '0002_marca_alter_equipo_options_alter_equipo_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='nombre_articulo',
            field=models.ForeignKey(blank=True, help_text='Nombre estándar del catálogo (opcional para autocompletado)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos', to='inventario.nombrearticulo', verbose_name='Nombre de Artículo (Catálogo)'),
        ),
        migrations.AddField(
            model_name='activo',
            name='sector',
            field=models.ForeignKey(blank=True, help_text='Sector o área del inventario (Música, Ed. Física, Laboratorio, etc.)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='inventario.sectorinventario', verbose_name='Sector/Taller'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='codigo_barras',
            field=models.CharField(blank=True, help_text='Código de barras del producto (dejar vacío para auto-generar desde el código)', max_length=100, null=True, unique=True, verbose_name='Código de Barras'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='inventario.marca', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='activo',
            name='modelo',
            field=models.ForeignKey(blank=True, help_text='Selecciona primero la marca para filtrar modelos', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activos', to='inventario.modelo', verbose_name='Modelo'),
        ),
    ]
