# Generated by Django 5.2.7 on 2025-10-26 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eliminado', models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('icono', models.CharField(default='bell', help_text='Nombre del icono a mostrar', max_length=50, verbose_name='Icono')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='Color (Hex)')),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=10, verbose_name='Prioridad')),
                ('enviar_email', models.BooleanField(default=False, help_text='Indica si se debe enviar email además de notificación en el sistema', verbose_name='Enviar Email')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Tipo de Notificación',
                'verbose_name_plural': 'Tipos de Notificaciones',
                'db_table': 'notificacion_tipo',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, help_text='Estado activo/inactivo del registro', verbose_name='Activo')),
                ('eliminado', models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('enlace', models.CharField(blank=True, help_text='URL a la que debe redirigir la notificación', max_length=255, null=True, verbose_name='Enlace')),
                ('modulo', models.CharField(blank=True, help_text='Módulo del sistema relacionado (compras, solicitudes, etc.)', max_length=50, null=True, verbose_name='Módulo')),
                ('referencia_id', models.IntegerField(blank=True, help_text='ID del objeto relacionado', null=True, verbose_name='ID de Referencia')),
                ('referencia_tipo', models.CharField(blank=True, help_text='Tipo de objeto relacionado (OrdenCompra, Solicitud, etc.)', max_length=50, null=True, verbose_name='Tipo de Referencia')),
                ('leida', models.BooleanField(default=False, verbose_name='Leída')),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Lectura')),
                ('archivada', models.BooleanField(default=False, verbose_name='Archivada')),
                ('email_enviado', models.BooleanField(default=False, verbose_name='Email Enviado')),
                ('fecha_envio_email', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Envío Email')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_expiracion', models.DateTimeField(blank=True, help_text='Fecha después de la cual la notificación se oculta automáticamente', null=True, verbose_name='Fecha de Expiración')),
                ('usuario_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Destino')),
                ('usuario_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Origen')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notificaciones', to='notificaciones.tiponotificacion', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'db_table': 'notificacion',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['usuario_destino', '-fecha_creacion'], name='notificacio_usuario_38dab9_idx'), models.Index(fields=['usuario_destino', 'leida'], name='notificacio_usuario_ffb62c_idx'), models.Index(fields=['tipo', '-fecha_creacion'], name='notificacio_tipo_id_e4ad6e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionNotificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, help_text='Estado activo/inactivo del registro', verbose_name='Activo')),
                ('eliminado', models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización')),
                ('notificacion_sistema', models.BooleanField(default=True, help_text='Recibir notificaciones en el sistema', verbose_name='Notificación en Sistema')),
                ('notificacion_email', models.BooleanField(default=True, help_text='Recibir notificaciones por correo electrónico', verbose_name='Notificación por Email')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_notificaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('tipo_notificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones', to='notificaciones.tiponotificacion', verbose_name='Tipo de Notificación')),
            ],
            options={
                'verbose_name': 'Configuración de Notificación',
                'verbose_name_plural': 'Configuraciones de Notificaciones',
                'db_table': 'notificacion_configuracion',
                'ordering': ['usuario', 'tipo_notificacion'],
                'unique_together': {('usuario', 'tipo_notificacion')},
            },
        ),
    ]
