# Generated by Django 5.2.7 on 2025-10-31 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='codigo_barras',
            field=models.CharField(blank=True, help_text='Código de barras del producto (dejar vacío para auto-generar)', max_length=100, null=True, unique=True, verbose_name='Código de Barras'),
        ),
    ]
