# Generated by Django 5.2.7 on 2025-10-31 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0002_articulo_codigo_barras'),
        ('inventario', '0002_marca_alter_equipo_options_alter_equipo_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='modelo',
            field=models.ForeignKey(blank=True, help_text='Selecciona primero la marca para filtrar modelos', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articulos', to='inventario.modelo', verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='nombre_articulo',
            field=models.ForeignKey(blank=True, help_text='Nombre estándar del catálogo (opcional para autocompletado)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articulos', to='inventario.nombrearticulo', verbose_name='Nombre de Artículo (Catálogo)'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='sector',
            field=models.ForeignKey(blank=True, help_text='Sector o área del inventario (Música, Ed. Física, Laboratorio, etc.)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articulos', to='inventario.sectorinventario', verbose_name='Sector/Taller'),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='articulos', to='inventario.marca', verbose_name='Marca'),
        ),
    ]
