# Generated by Django 5.2.7 on 2025-10-31 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bodega', '0002_articulo_codigo_barras'),
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, help_text='Estado activo/inactivo del registro', verbose_name='Activo')),
                ('eliminado', models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Marca')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('logo_url', models.URLField(blank=True, null=True, verbose_name='URL del Logo')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'db_table': 'inventario_marca',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='equipo',
            options={'ordering': ['codigo'], 'permissions': [('gestionar_equipos', 'Puede gestionar equipos'), ('asignar_equipos', 'Puede asignar equipos a usuarios/talleres'), ('ver_mantenimientos', 'Puede ver historial de mantenimientos')], 'verbose_name': 'Equipo', 'verbose_name_plural': 'Equipos'},
        ),
        migrations.AlterField(
            model_name='equipo',
            name='activo',
            field=models.BooleanField(default=True, help_text='Estado activo/inactivo del registro', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='eliminado',
            field=models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='mantenimientoequipo',
            name='activo',
            field=models.BooleanField(default=True, help_text='Estado activo/inactivo del registro', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='mantenimientoequipo',
            name='eliminado',
            field=models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado'),
        ),
        migrations.AlterField(
            model_name='mantenimientoequipo',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización'),
        ),
        migrations.AlterField(
            model_name='mantenimientoequipo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='taller',
            name='activo',
            field=models.BooleanField(default=True, help_text='Estado activo/inactivo del registro', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='taller',
            name='eliminado',
            field=models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado'),
        ),
        migrations.AlterField(
            model_name='taller',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización'),
        ),
        migrations.AlterField(
            model_name='taller',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='tipoequipo',
            name='activo',
            field=models.BooleanField(default=True, help_text='Estado activo/inactivo del registro', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='tipoequipo',
            name='eliminado',
            field=models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado'),
        ),
        migrations.AlterField(
            model_name='tipoequipo',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización'),
        ),
        migrations.AlterField(
            model_name='tipoequipo',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación'),
        ),
        migrations.CreateModel(
            name='NombreArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, help_text='Estado activo/inactivo del registro', verbose_name='Activo')),
                ('eliminado', models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código/SKU')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Artículo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('categoria_recomendada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nombres_articulos', to='bodega.categoria', verbose_name='Categoría Recomendada')),
            ],
            options={
                'verbose_name': 'Nombre de Artículo',
                'verbose_name_plural': 'Nombres de Artículos',
                'db_table': 'inventario_nombre_articulo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SectorInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, help_text='Estado activo/inactivo del registro', verbose_name='Activo')),
                ('eliminado', models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Sector')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sectores_inventario_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable del Sector')),
            ],
            options={
                'verbose_name': 'Sector de Inventario',
                'verbose_name_plural': 'Sectores de Inventario',
                'db_table': 'inventario_sector',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, help_text='Estado activo/inactivo del registro', verbose_name='Activo')),
                ('eliminado', models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código del Modelo')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Modelo')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modelos', to='inventario.marca', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
                'db_table': 'inventario_modelo',
                'ordering': ['marca__nombre', 'nombre'],
                'unique_together': {('marca', 'nombre')},
            },
        ),
    ]
