# Generated by Django 5.2.5 on 2025-09-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('apellidos', models.CharField(max_length=255)),
                ('rut', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('unidad', models.CharField(max_length=255)),
                ('estamento', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=255)),
                ('nombre_jefatura', models.CharField(max_length=255)),
                ('apellidos_jefatura', models.CharField(max_length=255)),
                ('rut_jefatura', models.CharField(max_length=20)),
                ('email_jefatura', models.EmailField(max_length=254)),
                ('unidad_jefatura', models.CharField(max_length=255)),
                ('estamento_jefatura', models.CharField(max_length=255)),
                ('cargo_jefatura', models.CharField(max_length=255)),
                ('sistemas', models.JSONField()),
                ('permisos', models.TextField(blank=True)),
                ('homologacion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='pendiente', max_length=50)),
            ],
        ),
    ]
