# Generated by Django 5.2.7 on 2025-11-01 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
        ('solicitudes', '0005_detallesolicitud_articulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='solicitudes',
            field=models.ManyToManyField(blank=True, help_text='Solicitudes aprobadas que originan esta orden de compra', related_name='ordenes_compra', to='solicitudes.solicitud', verbose_name='Solicitudes Asociadas'),
        ),
    ]
