# Generated by Django 5.2.7 on 2025-11-01 14:05

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_ordencompra_solicitudes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleordencompra',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Unitario'),
        ),
        migrations.AlterField(
            model_name='detalleordencompraarticulo',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Unitario'),
        ),
    ]
