# Generated by Django 5.2.7 on 2025-11-01 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_alter_detalleordencompra_precio_unitario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoRecepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eliminado', models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('requiere_orden', models.BooleanField(default=False, verbose_name='Requiere Orden de Compra')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Tipo de Recepción',
                'verbose_name_plural': 'Tipos de Recepción',
                'db_table': 'compra_tipo_recepcion',
                'ordering': ['codigo'],
            },
        ),
        migrations.AlterField(
            model_name='recepcionarticulo',
            name='numero',
            field=models.CharField(max_length=30, unique=True, verbose_name='Número de Recepción'),
        ),
        migrations.AddField(
            model_name='recepcionarticulo',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recepciones_articulos', to='compras.tiporecepcion', verbose_name='Tipo de Recepción'),
        ),
    ]
