# Generated by Django 5.2.7 on 2025-10-26 03:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activos', '0003_tipomovimientoactivo_ubicacion_movimientoactivo_and_more'),
        ('bodega', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoBaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eliminado', models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('color', models.CharField(default='#6c757d', max_length=7, verbose_name='Color (Hex)')),
                ('es_inicial', models.BooleanField(default=False, verbose_name='Estado Inicial')),
                ('es_final', models.BooleanField(default=False, verbose_name='Estado Final')),
                ('permite_edicion', models.BooleanField(default=True, verbose_name='Permite Edición')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Estado de Baja',
                'verbose_name_plural': 'Estados de Bajas',
                'db_table': 'baja_estado',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='MotivoBaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eliminado', models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('requiere_autorizacion', models.BooleanField(default=True, verbose_name='Requiere Autorización')),
                ('requiere_documento', models.BooleanField(default=False, help_text='Indica si se debe adjuntar un documento de respaldo', verbose_name='Requiere Documento')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Motivo de Baja',
                'verbose_name_plural': 'Motivos de Baja',
                'db_table': 'baja_motivo',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='BajaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, help_text='Estado activo/inactivo del registro', verbose_name='Activo')),
                ('eliminado', models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número de Baja')),
                ('fecha_baja', models.DateField(verbose_name='Fecha de Baja')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('fecha_autorizacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Autorización')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('notas_autorizacion', models.TextField(blank=True, null=True, verbose_name='Notas de Autorización')),
                ('documento', models.FileField(blank=True, null=True, upload_to='bajas_inventario/%Y/%m/', verbose_name='Documento de Respaldo')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Total')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Modificación')),
                ('autorizador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bajas_autorizadas', to=settings.AUTH_USER_MODEL, verbose_name='Autorizador')),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bajas_inventario', to='bodega.bodega', verbose_name='Bodega')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bajas_solicitadas', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bajas', to='bajas_inventario.estadobaja', verbose_name='Estado')),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bajas', to='bajas_inventario.motivobaja', verbose_name='Motivo')),
            ],
            options={
                'verbose_name': 'Baja de Inventario',
                'verbose_name_plural': 'Bajas de Inventario',
                'db_table': 'baja_inventario',
                'ordering': ['-fecha_baja', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='DetalleBaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eliminado', models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Cantidad')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Unitario')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor Total')),
                ('lote', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lote')),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Serie')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_baja', to='activos.activo', verbose_name='Activo')),
                ('baja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='bajas_inventario.bajainventario', verbose_name='Baja')),
            ],
            options={
                'verbose_name': 'Detalle de Baja',
                'verbose_name_plural': 'Detalles de Bajas',
                'db_table': 'baja_detalle',
                'ordering': ['baja', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HistorialBaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True, help_text='Estado activo/inactivo del registro', verbose_name='Activo')),
                ('eliminado', models.BooleanField(default=False, help_text='Estado eliminado/no eliminado del registro', verbose_name='Eliminado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación del registro', verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, help_text='Fecha y hora de última actualización', verbose_name='Fecha de Actualización')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Cambio')),
                ('baja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='bajas_inventario.bajainventario', verbose_name='Baja')),
                ('estado_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historiales_anterior', to='bajas_inventario.estadobaja', verbose_name='Estado Anterior')),
                ('estado_nuevo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historiales_nuevo', to='bajas_inventario.estadobaja', verbose_name='Estado Nuevo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_estado_baja', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Historial de Baja',
                'verbose_name_plural': 'Historial de Bajas',
                'db_table': 'baja_historial',
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
