# Generated by Django 5.2 on 2025-08-24 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuariosistema',
            options={'ordering': ['username'], 'permissions': [('can_manage_unit_users', 'Puede gestionar usuarios de su unidad'), ('can_view_unit_reports', 'Puede ver reportes de su unidad'), ('can_create_mass_emails', 'Puede crear envíos masivos de correo'), ('can_manage_email_lists', 'Puede gestionar listas de correo'), ('can_view_email_analytics', 'Puede ver analíticas de envíos'), ('can_manage_email_templates', 'Puede gestionar plantillas de correo')], 'verbose_name': 'Usuario del Sistema', 'verbose_name_plural': 'Usuarios del Sistema'},
        ),
    ]
